project:
  type: website
  output-dir: docs

website:
  title: ""
  site-url: "https://workmans-friend.github.io/pint-of-plain"
  favicon: images/noun-pint-1244806.svg
  open-graph:
    title: "The Workman's Friend"
    description: "The Workman's Friend by Flann O'Brian"
  twitter-card:
    title: "The Workman's Friend"
    description: "The Workman's Friend by Flann O'Brian"
  repo-url: https://github.com/workmans-friend
format:
  closeread-html:
    theme: darkly
